package eu.wohlben.qits.workspaces.api;

import static io.restassured.RestAssured.given;

import io.quarkus.test.junit.QuarkusTest;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.junit.jupiter.api.Test;

/**
 * Writes {@code docs/openapi.yml} as a side effect of the suite, the same way the monorepo's own
 * {@code OpenApiSchemaExportTest} does. Checking the document in is what turns an API change into a
 * reviewable diff instead of something a caller discovers at runtime.
 *
 * <p>This is a test only because {@code @QuarkusTest} is the cheapest way to stand the application
 * up and read its own {@code /q/openapi}. It asserts nothing — the assertion is the diff.
 *
 * <p>The test classpath is indexed too, so any {@code @Path} resource under {@code src/test} lands
 * in the committed document unless it is {@code @Operation(hidden = true)} — see {@code
 * IdentityEchoResource}. The raw Vert.x routes ({@code CaptureCorsRoute}, {@code ContainerProxyRoute})
 * and the daemon control socket appear in no document at all; they are not JAX-RS.
 */
@QuarkusTest
public class OpenApiSchemaExportTest {

  /**
   * Where the document is served from. Read rather than written literally: {@code /q/*} is outside
   * {@code quarkus.rest.path} and moves only with this key, so a hard-coded {@code /q/openapi} would
   * simply 404 the day the service's segment changed — and this test asserts nothing else, so the
   * 404 is the only thing that would tell you.
   */
  @ConfigProperty(name = "quarkus.http.non-application-root-path", defaultValue = "/q")
  String nonApplicationRootPath;

  @Test
  public void exportOpenApiSchema() throws Exception {
    String schema =
        given()
            .when()
            .get(RootPath.prefix(nonApplicationRootPath) + "/openapi")
            .then()
            .statusCode(200)
            .extract()
            .asString();

    Path docsDir = Paths.get("../docs");
    if (!Files.exists(docsDir)) {
      Files.createDirectories(docsDir);
    }

    String header =
        "# THIS FILE IS GENERATED BY OpenApiSchemaExportTest — DO NOT EDIT MANUALLY.\n"
            + "# Run `./mvnw -pl service test -Dtest=OpenApiSchemaExportTest` to regenerate.\n";

    Files.writeString(docsDir.resolve("openapi.yml"), header + schema);
  }
}
